name: 'JIRA PR Verification GitHub Action'
description: 'JIRA Pull Request Verification for GitHub Actions'
author: 'Farhad Safarov'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  title-regex:
    description: 'Title regex to match, should contain a <tickets> group'
    required: true
  title-ticket-delimiter:
    description: "Ticket delimiter in pull request title"
    required: false
    default: ','
  branch-name-regex:
    description: 'branch name regex to match, should contain a <tickets> group'
    required: true
  branch-name-ticket-delimiter:
    description: "ticket delimiter in branch name"
    required: false
    default: '/'
  github-token:
    description: 'Github token'
    required: true
  atlassian-token:
    description: 'Atlassian token'
    required: true
  atlassian-domain:
    description: 'Your atlassian domain'
    required: true
branding:
  icon: 'edit-3'
  color: 'blue'
