name: 'PR Lint GitHub Action'
description: 'PR Lint for GitHub Actions'
author: 'Farhad Safarov'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  ticket-regex:
    description: 'Ticket regex to match'
    required: true
  github-token:
    description: 'Github token'
    required: true
  atlassian-token:
    description: 'Atlassian token'
    required: true
  atlassian-domain:
    description: 'Your atlassian domain'
    required: true
branding:
  icon: 'edit-3'
  color: 'blue'
