name: PR lint

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  pr-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: odedlaz/pr-ensure-jira@master
      with:
        title-regex: '^(\[[a-z ]*\]|Bump) '
